version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/i8g4q7b2
      - REPOSITORY_NAME="ecr"      
      - REPOSITORY_URI=public.ecr.aws/i8g4q7b2/ecr
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_NAME:latest -f ./Dockerpipe1/blob/main/Service1/dockerfile . 
      - docker tag ecr:latest public.ecr.aws/i8g4q7b2/ecr:latest
      - docker tag ecr:latest public.ecr.aws/i8g4q7b2/ecr:latest:docker push public.ecr.aws/i8g4q7b2/ecr:latest
  post_build:
    commands:
      - docker push public.ecr.aws/i8g4q7b2/ecr:latest
      - docker push public.ecr.aws/i8g4q7b2/ecr:latest docker tag ecr:latest public.ecr.aws/i8g4q7b2/ecr:latest
      - printf '[{"name":"container-1","imageUri":"%s"}]' public.ecr.aws/i8g4q7b2/ecr:latest > imagedefinitions-1.json

artifacts:
  files: imagedefinitions-1.json
