version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v4j2a7d2
      - 
      - REPOSITORY_NAME_1="ecr-repo-1" 
      - REPOSITORY_NAME_2="ecr-repo-2"
      - REPOSITORY_NAME_3="ecr-repo-3"
      - REPOSITORY_NAME_4="ecr-repo-4"
      - REPOSITORY_NAME_5="ecr-repo-5"
      - REPOSITORY_NAME_6="ecr-repo-6"
             

      - REPOSITORY_URI-1=public.ecr.aws/v4j2a7d2/ecr-repo-1
      - REPOSITORY_URI-2=public.ecr.aws/v4j2a7d2/ecr-repo-2
      - REPOSITORY_URI-3=public.ecr.aws/v4j2a7d2/ecr-repo-3
      - REPOSITORY_URI-4=public.ecr.aws/v4j2a7d2/ecr-repo-4
      - REPOSITORY_URI-5=public.ecr.aws/v4j2a7d2/ecr-repo-5
      - REPOSITORY_URI-6=public.ecr.aws/v4j2a7d2/ecr-repo-6
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_NAME-1:latest-1 -f ./service-1/dockerfile .
      - docker build -t $REPOSITORY_NAME-2:latest-2 -f ./service-1/dockerfile . 
      - docker build -t $REPOSITORY_NAME-3:latest-3 -f ./service-1/dockerfile .
      - docker build -t $REPOSITORY_NAME-3:latest-3 -f ./service-1/dockerfile .
      - docker build -t $REPOSITORY_NAME-4:latest-4 -f ./service-1/dockerfile .
      - docker build -t $REPOSITORY_NAME-5:latest-5 -f ./service-1/dockerfile .
      - docker build -t $REPOSITORY_NAME-6:latest-6 -f ./service-1/dockerfile .
      - docker tag $REPOSITORY_NAME-1:latest $REPOSITORY_URI:latest-1
      - docker tag $REPOSITORY_NAME-2:latest $REPOSITORY_URI:latest-2
      - docker tag $REPOSITORY_NAME-3:latest $REPOSITORY_URI:latest-3
      - docker tag $REPOSITORY_NAME-4:latest $REPOSITORY_URI:latest-4
      - docker tag $REPOSITORY_NAME-5:latest $REPOSITORY_URI:latest-6
      - docker tag $REPOSITORY_NAME-5:latest $REPOSITORY_URI:latest-6 
      - docker tag $REPOSITORY_NAME-1:latest $REPOSITORY_URI:$IMAGE_TAG-1
      - docker tag $REPOSITORY_NAME-2:latest $REPOSITORY_URI:$IMAGE_TAG-2
      - docker tag $REPOSITORY_NAME-3:latest $REPOSITORY_URI:$IMAGE_TAG-3
      - docker tag $REPOSITORY_NAME-4:latest $REPOSITORY_URI:$IMAGE_TAG-4
      - docker tag $REPOSITORY_NAME-5:latest $REPOSITORY_URI:$IMAGE_TAG-5
      - docker tag $REPOSITORY_NAME-6:latest $REPOSITORY_URI:$IMAGE_TAG-6
  post_build:
    commands:
      - docker push $REPOSITORY_URI-1:latest-1
      - docker push $REPOSITORY_URI-2:latest-2
      - docker push $REPOSITORY_URI-3:latest-3
      - docker push $REPOSITORY_URI-4:latest-4
      - docker push $REPOSITORY_URI-5:latest-5
      - docker push $REPOSITORY_URI-6:latest-6
      - docker push $REPOSITORY_URI-1:$IMAGE_TAG-1 
      - docker push $REPOSITORY_URI-2:$IMAGE_TAG-2 
      - docker push $REPOSITORY_URI-3:$IMAGE_TAG-3
      - docker push $REPOSITORY_URI-4:$IMAGE_TAG-4 
      - docker push $REPOSITORY_URI-5:$IMAGE_TAG-5
      - docker push $REPOSITORY_URI-6:$IMAGE_TAG-6
      - printf '[{"name":"container-1","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions-1.json
      - printf '[{"name":"container-2","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions-2.json
      - printf '[{"name":"container-3","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions-3.json
      - printf '[{"name":"container-4","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions-4.json
      - printf '[{"name":"container-5","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions-6.json
      - printf '[{"name":"container-6","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions-7.json

artifacts:
  files: imagedefinitions-1.json
  files: imagedefinitions-2.json
  files: imagedefinitions-3.json
  files: imagedefinitions-4.json
  files: imagedefinitions-5.json
  files: imagedefinitions-6.json
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/m7n0j1n1
      - REPOSITORY_NAME="ecr"      
      - REPOSITORY_URI=public.ecr.aws/m7n0j1n1/ecr
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_NAME:service1 --build-arg file_path=./service1/index.html .
      - docker build -t $REPOSITORY_NAME:service2 --build-arg file_path=./service2/index.html .
      - docker build -t $REPOSITORY_NAME:service3 --build-arg file_path=./service3/index.html .
      - docker build -t $REPOSITORY_NAME:service4 --build-arg file_path=./service4/index.html .
      - docker build -t $REPOSITORY_NAME:service5 --build-arg file_path=./service5/index.html .
      - docker build -t $REPOSITORY_NAME:service6 --build-arg file_path=./service6/index.html .

      
      
      - docker tag $REPOSITORY_NAME:service1 $REPOSITORY_URI:service1
      - docker tag $REPOSITORY_NAME:service2 $REPOSITORY_URI:service2
      - docker tag $REPOSITORY_NAME:service3 $REPOSITORY_URI:service3
      - docker tag $REPOSITORY_NAME:service4 $REPOSITORY_URI:service4
      - docker tag $REPOSITORY_NAME:service5 $REPOSITORY_URI:service5
      - docker tag $REPOSITORY_NAME:service6 $REPOSITORY_URI:service6


      #- docker tag $REPOSITORY_NAME:latest $REPOSITORY_URI:$IMAGE_TAG


  post_build:
    commands:
      - docker push $REPOSITORY_URI:service1
      - docker push $REPOSITORY_URI:service2
      - docker push $REPOSITORY_URI:service3
      - docker push $REPOSITORY_URI:service4
      - docker push $REPOSITORY_URI:service5
      - docker push $REPOSITORY_URI:service6
      
      #- docker push $REPOSITORY_URI:$IMAGE_TAG

      - printf '[{"name":"golang-container-1","imageUri":"%s"}]' $REPOSITORY_URI:service1 > imagedefinitions-1.json
      - printf '[{"name":"golang-container-1","imageUri":"%s"}]' $REPOSITORY_URI:service2 > imagedefinitions-2.json
      - printf '[{"name":"golang-container-1","imageUri":"%s"}]' $REPOSITORY_URI:service3 > imagedefinitions-3.json
      - printf '[{"name":"golang-container-1","imageUri":"%s"}]' $REPOSITORY_URI:service4 > imagedefinitions-4.json
      - printf '[{"name":"golang-container-1","imageUri":"%s"}]' $REPOSITORY_URI:service5 > imagedefinitions-5.json
      - printf '[{"name":"golang-container-1","imageUri":"%s"}]' $REPOSITORY_URI:service6 > imagedefinitions-6.json


artifacts:
  files: 
    - imagedefinitions-1.json
    - imagedefinitions-2.json
    - imagedefinitions-3.json
    - imagedefinitions-4.json
    - imagedefinitions-5.json
    - imagedefinitions-6.json
  

  

  
